### ISSUE TITLE
No valid exports main found 

### ISSUE THREAD

**Issue by purzyk** [mitchheddles/webpack-handlebars-static#6]
Hello
I was trying to install your webpack starter theme, but ive got this error aftrer npm run build
any chances you could help me, please?

`Error: No valid exports main found for 'E:\www\testhtml\webpack-handlebars-static-master\node_modules\colorette'
    at resolveExportsTarget (internal/modules/cjs/loader.js:625:9)
    at applyExports (internal/modules/cjs/loader.js:502:14)
    at resolveExports (internal/modules/cjs/loader.js:551:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:657:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:960:27)
    at Function.Module._load (internal/modules/cjs/loader.js:855:27)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (E:\www\testhtml\webpack-handlebars-static-master\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.<anonymous> (E:\www\testhtml\webpack-handlebars-static-master\node_modules\autoprefixer\lib\autoprefixer.js:5:17)
    at Module._compile (E:\www\testhtml\webpack-handlebars-static-master\node_modules\v8-compile-cache\v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (E:\www\testhtml\webpack-handlebars-static-master\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.<anonymous> (E:\www\testhtml\webpack-handlebars-static-master\node_modules\postcss-preset-env\index.js:5:36)
    at Module._compile (E:\www\testhtml\webpack-handlebars-static-master\node_modules\v8-compile-cache\v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (E:\www\testhtml\webpack-handlebars-static-master\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.<anonymous> (E:\www\testhtml\webpack-handlebars-static-master\webpack.config.js:6:26)
    at Module._compile (E:\www\testhtml\webpack-handlebars-static-master\node_modules\v8-compile-cache\v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (E:\www\testhtml\webpack-handlebars-static-master\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at WEBPACK_OPTIONS (E:\www\testhtml\webpack-handlebars-static-master\node_modules\webpack-cli\bin\utils\convert-argv.js:114:13)
    at requireConfig (E:\www\testhtml\webpack-handlebars-static-master\node_modules\webpack-cli\bin\utils\convert-argv.js:116:6)
    at E:\www\testhtml\webpack-handlebars-static-master\node_modules\webpack-cli\bin\utils\convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (E:\www\testhtml\webpack-handlebars-static-master\node_modules\webpack-cli\bin\utils\convert-argv.js:121:15)
    at E:\www\testhtml\webpack-handlebars-static-master\node_modules\webpack-cli\bin\cli.js:71:45
    at Object.parse (E:\www\testhtml\webpack-handlebars-static-master\node_modules\yargs\yargs.js:576:18) {
  code: 'MODULE_NOT_FOUND'

}`

**Comment by mitchheddles** [comment]
Hey @purzyk sorry for the late reply, can you share the project and your node version?
